### ISSUE TITLE
Improve discoverability of your work on HF

### ISSUE THREAD

**Issue by NielsRogge** [WeihuangLin/INF-LLaVA#1]
### feature

Hi,

Niels here from the open-source team at Hugging Face. I discovered your work through the paper page: https://huggingface.co/papers/2407.16198 (feel free to claim the paper so that it appears at your HF account!).

However there are a couple of things which could improve the discoverability of your work, which I've listed below.

### Add a model card

I see the models are already on the hub, but there are no model cards, e.g. https://huggingface.co/WeihuangLin/INF-LLaVA-sft

It would be great to add it so that people know what the models are about :) See here for some tips: https://huggingface.co/docs/hub/en/model-cards.

Moreover, the models could be linked with the paper, see here on how to do that: https://huggingface.co/docs/hub/en/model-cards#linking-a-paper

### Integration with the Transformers library

We offer https://huggingface.co/docs/transformers/custom_models which ensures your model can be loaded using Transformers, with `trust_remote_code=True`. This would make it easier to get started with your models in a few lines of code.

Let me know if you need any help regarding this!

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by WeihuangLin** [comment]
Thank you very much for your suggestions. We will make improvements based on the information you provided.

**Comment by NielsRogge** [comment]
Hi @WeihuangLin it seems the issue is still open
